# Large multimodal model setting.
lmm:
  model_name: Qwen/Qwen2-VL-7B-Instruct
  base_url: http://localhost:12345/v1
  api_key: token-abc123


dataset:
  name: coco-classificaiton
  train_root: '[your path]/COCO2014/train2014/'
  val_root: '[your path]/COCO2014/val2014/'
  clip_download_root: 'clip_models'
  class_name_path: './data/mscoco/category.json'
  train_metadata_path: './data/mscoco/train_anno.json'
  test_metadata_path: './data/mscoco/val_anno.json'
  # for reproducibility
  missing_config: ./src/data/mscoco/missing-config/train-mixed-0.3.json
  missing_set: test  # ['train', 'test']


# Inference setting.
inference:
  domain: general
  save_path: ./coco/knowledge-extraction/train-mixed-0.3
  save_intervals: 16
  seed: 2025
  max_token: 512
  temperature: 0.1




