dataset:
  name: coco-classificaiton
  train_root: '[your path]/COCO2014/train2014/'
  val_root: '[your path]/COCO2014/val2014/'
  clip_download_root: 'clip_models'
  class_name_path: './data/mscoco/category.json'
  train_metadata_path: './data/mscoco/train_anno.json'
  test_metadata_path: './data/mscoco/val_anno.json'
  missing_config: None
  is_missing: false
  keep_raw: false
  merge_metadata: false


model:
  name: CLIPModelBaseline
  clip_download_root: 'clip_models'
  num_labels: 80
  finetune: true
  dtype: fp32


train:
  exp_name: bs-32-th-0.5-a-1-g-2-ft-first
  ckpt_dir: './coco-baseline/'
  lr: 1e-4
  epochs: 30
  batch_size: 32
  threshold: 0.5
  seed: 2025

loss:
  type: 'focal'
  alpha: 1.0
  gamma: 2