# Large multimodal model setting.
lmm:
  model_name: Qwen/Qwen2-VL-7B-Instruct
  base_url: http://localhost:12345/v1
  api_key: token-abc123


dataset:
  name: mmimdb
  train_root: '[your path]/mmimdb/mmimdb/dataset/'
  val_root: '[your path]/mmimdb/mmimdb/dataset/'
  clip_download_root: 'clip_models'
  class_name_path: './data/mmimdb/category.json'
  train_metadata_path: './data/mmimdb/trainset.json'
  test_metadata_path: './data/mmimdb/testset.json'
  # for reproducibility
  missing_config: ./src/data/mmimdb/missing-config/train-mixed-0.3.json
  missing_set: train  # ['train', 'test']



# Inference setting.
inference:
  domain: general
  save_path: ./mmimdb/knowledge-extraction/train-mixed-0.3
  save_intervals: 16
  seed: 2025
  max_token: 512
  temperature: 0.1




